# Cloudflare Pages + D1 + KV

name = "rugu-cloud"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "rugu-cloud-db"
database_id = "bea3b101-156a-4d97-a3b1-b1f0c9e2c9f9"

[[kv_namespaces]]
binding = "SESSIONS"
id = "1c75f37427f346dfacccb7b486476e01"
